### PR TITLE
Nav Backpack v2.0 (RW-3)

### PR DESCRIPTION
**Pull request by aaronbeekay**

### CODE REVIEW

**Comment by aaronbeekay** [comment]
@strugglebus I opened this PR for you since we're almost done here.

Changes before we can put this through:

## Documentation
* [ ] You should delete the files from the last version of this board ("NavModule_v1.0_BOM.xlsx", etc)
* [ ] Needs BOM
* [ ] Needs schematic + board PDFs

## Board/schematic
* Your DRC errors look good as of 02828b7. 
* [ ] Make sure that text on the silkscreen layer is in "Vector" font.
* [ ] You should fix or approve the ERC warnings you ahve.

Other than that, looking great. We can get this made very soon.

**Comment by aaronbeekay** [comment]
@strugglebus - almost there, but your BOM needs to be modified to fit the standard format for the team - check out [this wiki page](http://wiki.buckeyecurrent.com/w/ECAD_design_standards#Bill_of_Materials) for details on the format

**Comment by lordnathan0** [comment]
I have also noticed the GPS communication lines are not connected to the microcontroller. These need to be added to get GPS data =)

**Comment by aaronbeekay** [comment]
Awesome @strugglebus, looking good.

@lordnathan0, can you confirm that the GPS pins will work for you as designed? If so, this is good to go.

**Comment by lordnathan0** [comment]
@aaronbeekay @strugglebus  to confirm the GPS pins you choose will work. I can use any pin from GPIO0 to GPIO31

**Pull request merged**
